### ISSUE TITLE
Video Loop

### ISSUE THREAD

**Issue by philimi** [Minibumphead/Philimi#3]
Videos im Loop abschließen. (Auf Projektseiten) 
Steuerelemnte vom Player ausblenden.

**Comment by philimi** [comment]
<video class="video" controls="controls" autoplay muted>
	<source src="mercedes/DATEINAME.av1.webm" type="video/webm; codecs=av01.0.08M.08">
	<source src="mercedes/DATEINAME.mp4" type="video/mp4">
	<source src="mercedes/DATEINAME.vp9.webm" type="video/webm; codecs=vp9">
</video>

**Comment by philimi** [comment]
```
<video class="video" controls="controls" autoplay muted>
	<source src="mercedes/DATEINAME.av1.webm" type="video/webm; codecs=av01.0.08M.08">
	<source src="mercedes/DATEINAME.mp4" type="video/mp4">
	<source src="mercedes/DATEINAME.vp9.webm" type="video/webm; codecs=vp9">
</video >
```

**Comment by Minibumphead** [comment]
<video class="video" autoplay muted>
                <source src="Projektbilder/Mercedes/timelapse1.mp4" type="video/mp4">
                <source src="movie.ogg" type="video/ogg">
</video>

Sollen die videos in dauerschleife durchlaufen? Was meinst du mit im Loop "abschliessen"?

**Comment by Minibumphead** [comment]
Damit sie dauerhaft laufen muss man einfach nur "loop" hinzufuegen
